### PR TITLE
Section 6-130-138

### PR DESCRIPTION
**Pull request by seanho96**
- add one-to-many association between users and articles
- replace hard coded names with article user
- downcase email before saving user
- add secure password field for user
- add new user signup form

### CODE REVIEW

**Review by tlkiong — COMMENTED** [review]
Explain what is the belongs to & has many relationship in the context of db

**Comment by seanho96** [comment]
In this case, where each article belongs to a user, meaning that each article in the articles table would have a reference id (user_id) pointing to a user. Setting the has many relationship for the user indicates that each instance of the model has zero or more instances of the article model.

**Comment by tlkiong** [comment]
A 1 to many is the exact as belongs to in RDBMS (relational database management systems)

2 tables have connection of one to many & belongs to when one table has the ID of the other as a foreign key.

The technical keyword here is `foreign key`. 

---

I specifically ask in context of db is because this is concepts outside of rails. Know the basics of this and you can use any RDBMS (postgres, MySQL, sqlite, etc). as the fundamental functionalities between all these are the same.

**Review by tlkiong — APPROVED** [review]

**Comment by seanho96** [comment]
I wanted to refer the reference id as the foreign key as that is my general understanding of DBs but why does Rails not have the foreign key attribute set by default? What does it do when you set that to true?

**Comment by tlkiong** [comment]
It doesn't have by default because the ORM (ActiveRecord) having those are what we call application level validations. 
If you want db level validations (which we always want to have), we do it in the migration file.

We always want db validations because if we want to next time, we can just change from rails to django or other framework and it'll still work cause of db validations (migrating db is hard). And, if we have other sources that input / extract data from db, with db validations, we won't get dirty data in it.

An example. Having db level validations for foreign keys will ensure someone who try to delete the parent record (owner of the foreign key) will either delete all the child record or throw error saying cannot delete that record unless all child record is deleted. Without this validation on the db but on rails will cause that person to be able to delete record from db. Then in the end, we will have orphaned data - data that have a foreign key reference but the data itself don't exist anymore

**Comment by seanho96** [comment]
So you're saying that in Rails with the ORM (ActiveRecord), relationships are handled on a Rails level by default and the foreign keys don't get created on the db itself? I tried querying on the Rails console for `Article.all` for e.g. and I do see the data referenced with `user_id`. Would there be a way to see the data via a RDBMS?

**Comment by tlkiong** [comment]
No no.
Rails don't magically create for you. You created the link yourself [here](https://github.com/seanho96/crud-operations/pull/10/files#diff-1aa5117f37a17d2e60fb1de6e6572a09dd15f570d3c91f82aa822e2b1c934429R3)

You can put the has many and belongs to on the model but do not have the xxx_id column in the db. However, you will get error when querying. Cause ActiveRecord will use the xxx_id to make that query

**Pull request merged**
